app:
  env: dev
  port: 8080

system:
  timezone: Asia/Bangkok

database:
  postgres:
    host: 172.17.0.1
    user: postgres
    password: postgres
    name: todo_fiber
    port: 5432
    sslmode: disable
    timezone: Asia/Bangkok
  
redis:
  host: localhost
  port: 6379
  password: